config/routes.rb
Rails.application.routes.draw do  

  root "profile#index"
  get "profile/index"
  get "profile/bestfriends"
  get "profile/compscifriends"
  get "profile/Family"
  get "profile/Girls"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    
  end

  def bestfriends
  end

  def compscifriends
  end

  def Family
  end

  def Girls
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Profile" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= favicon_link_tag 'butterfly.png', :rel => 'shortcut icon', :type => 'image/png' %>
    <%= favicon_link_tag 'butterfly.png', :rel => 'apple-touch-icon', :type => 'image/png' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :main %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= profile_index_path %>"><%= image_tag("butterfly.png", alt:"PROFILE", :class => "navbar-icon")%> Libby!</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= profile_Family_path %>"><i class="bi bi-flower1"></i> Family</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= profile_bestfriends_path %>"><i class="bi bi-gift-fill"></i> Besties</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= profile_compscifriends_path %>"><i class="bi bi-pc-display-horizontal"></i> CS Friends</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= profile_Girls_path %>"><i class="bi bi-envelope-open-heart"></i> The Girls</a>
          </li>
          
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid">
    <%= yield %>
  </div>
  

</body>
</html>